### ISSUE TITLE
Default path to `.data/`

### ISSUE THREAD

**Issue by ppvg** [SpoonX/wetland#107]
~~The `.data/` directory is always created, regardless of whether the default sqlite store is used.~~

~~It would be sweet if `path.dirname(store.connection.filename)` would be auto-created **after** the stores are loaded. That way it also works for any user-provided sqlite stores.~~
Edit: never mind, `.data` is always necessary.

The data dir is created relative to `process.cwd()`. It would probably be more intuitive if it were created relative to **`require.main.filename`**, i.e. in the same directory as the application's entrypoint (`index.js` or `server.js` or whatever).

**Comment by RWOverdijk** [comment]
This takes more consideration because of the cli. I'm closing this for now, until we can start solving problems :D

**Comment by ppvg** [comment]
I'll open a new ticket when I have a better proposal that considers the cli as well.

**Comment by RWOverdijk** [comment]
Might be good to link this ticket to https://github.com/SpoonX/wetland/issues/111
