### ISSUE TITLE
Primary key always generates an int; does not allow using a bigint as the primary key.

### ISSUE THREAD

**Issue by cpaulit** [SpoonX/wetland#201]
Great ORM, by the way.  I really like the conceptual foundation of it.

In a few projects I've worked on (JPA ORM), we've used long <-> bigint as both primary keys and foreign keys.  Mapping the id to a bigint does not work, because the migrator/schema generator always generates an int for the primary key field of an entity.

**Comment by RWOverdijk** [comment]
Good find. This could definitely be improved. It used to collect the type, which threw errors when using blobs. But this could be added back with a more descriptive message.

**Comment by RWOverdijk** [comment]
@cpaulit Doing my round of changes and issue replies. Would it be useful to make this an option? It sounds like the type of thing you wouldn't want to do for all entities individually.

**Comment by RWOverdijk** [comment]
Stop making me feel bad, bot.
