### ISSUE TITLE
Don't have the ability to specifiy microsends precision on date fields

### ISSUE THREAD

**Issue by cpaulit** [SpoonX/wetland#202]
MySQL and MariaDB allow DATE, TIME, DATETIME, and TIMESTAMP fields to be created with microsecond (0-6) configurations.

When needing the more precision than just the second, historically, we would store the date value as a bigint and have ORM custom serializers/deserializers that would convert between the date object and the persisted bigint.  Now, the databases have the ability to store that precision, and it would be a help to be able to have the schema generator generate them with precision as needed.

**Comment by RWOverdijk** [comment]
What would that look like? Basically anything possible with [knex](http://knexjs.org/) is possible with Wetland.

**Comment by cpaulit** [comment]
Normal:

CREATE TABLE t1 (d DATETIME);

With precision:

CREATE TABLE t2 (d DATETIME(6));

I took those from here:
https://mariadb.com/kb/en/mariadb/datetime/

Paul

**Comment by RWOverdijk** [comment]
@cpaulit I'm currently a bit busy, so I'll have time somewhere next week, and potentially Saturday. Could you check if it's possible in knex? If so, I'll tell you how to do it, and if needed add support for it. Otherwise, please forgive me for the delay.

**Comment by cpaulit** [comment]
I did not see this option in knex.

I'm getting ready to head out of town, and will be off the grid all next
week.  I'll check in after next week and see where things are.

**Comment by RWOverdijk** [comment]
In that case, as unfortunate as it might be, I see two options forward. The first is PR it into knexjs, the second is using raw queries, which I don't see as a viable option myself. I've never seen anyone use what you're describing, but it seems useful to have support for so I'd say a PR for knexjs is a nice way forward.

**Comment by cpaulit** [comment]
I looks like that will probably be the best.

Even Java's JPA specification didn't have that either, but Hibernate (JPA)
did allow us to implement customize serializers/deserializers for different
Java data types.  That's how we've gotten around the date microsecond
precision issue (for java types Date and Instant) in the past.

**Comment by RWOverdijk** [comment]
That might not be a bad idea in any case. :)
