### ISSUE TITLE
Add engine to entity mapping.

### ISSUE THREAD

**Issue by cpaulit** [SpoonX/wetland#203]
When building the create table in the schema generator, add ability to specify the table engine.  I believe that's available in Knex already.  We've used this quite a bit.

    create table user (
        id bigint not null auto_increment,
        . . .
        primary key (id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;

**Comment by RWOverdijk** [comment]
@cpaulit I added support for collate and charset recently. Adding support for the engine is similar. Would you like to make a PR if I show you how? Otherwise, like with the other issue, I'll look into it as soon as I have time.

The PR: https://github.com/SpoonX/wetland/pull/199

**Comment by cpaulit** [comment]
I saw that you have recently added those two options--both of which I
implemented because I typically use them.  As I mentioned in my other
email, I'll be off the grid all next week, and and now currently engaged in
getting ready for that excursion.  I check back when I return.

**Comment by RWOverdijk** [comment]
Alright :) Have fun doing your off-the-grid-type stuff.

**Comment by RWOverdijk** [comment]
@cpaulit I'll be closing these issues. The features have been added. :)
