### ISSUE TITLE
Unique constraint generating property name rather than column name.

### ISSUE THREAD

**Issue by cpaulit** [SpoonX/wetland#205]
When using this entity mapping:
```mapping.manyToOne('family', {targetEntity: 'Family', inversedBy: 'members', joinColumn: 'family_id'});```
And adding the constraint:
```mapping.uniqueConstraint(['family', 'name']);```
This owned property is correctly generated as:
```family_id` int unsigned null```
But the unique constraint is generated as this:
```alter table `family_member` add unique `family_member_family_name_unique`(`family`, `name`);```
As you can see, that will fail because the column name really is 'family_id'.

To compensate, if I try and do this:
```mapping.uniqueConstraint(['family_id', 'name']);```
an exception is thrown.
```/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/Mapping.js:187
            throw new Error(`Unknown field "${property}" supplied on entity "${this.getEntityName()}".`);
            ^

Error: Unknown field "family_id" supplied on entity "FamilyMember".
    at Mapping.getField (/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/Mapping.js:187:19)
    at Mapping.getColumnName (/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/Mapping.js:171:21)
    at properties.map.column (/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/Mapping.js:270:46)
    at Array.map (native)
    at Mapping.getColumnNames (/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/Mapping.js:270:27)
    at unprocessed.forEach.constraint (/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/Mapping.js:369:31)
    at Array.forEach (native)
    at Mapping.processUniqueConstraints (/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/Mapping.js:365:21)
    at Mapping.completeMapping (/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/Mapping.js:763:14)
    at Mapping.serializable (/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/Mapping.js:772:21)
    at SnapshotManager.getSerializable (/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/SnapshotManager.js:113:61)
    at SchemaManager.prepare (/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/SchemaManager.js:63:37)
    at SchemaManager.getSQL (/usr/local/lib/node_modules/wetland-cli/node_modules/wetland/dist/src/SchemaManager.js:21:21)
    at Command.program.command.description.action.options (/usr/local/lib/node_modules/wetland-cli/dist/wetland-migrator.js:105:28)
    at Command.listener (/usr/local/lib/node_modules/wetland-cli/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
```

**Comment by RWOverdijk** [comment]
That's not [how to use joinColumn](https://wetland.spoonx.org/API/mapping.html#join-column-options). That option also [doesn't exist](https://wetland.spoonx.org/API/mapping.html#relationship-options).

The case is interesting, though. You want to keep your relationships unique. In this case, If the mapping doesn't exist it will throw an error. The way it currently works is that you register your own joinColumns. Those can't be used in constraints (which, in terms of database design is a bit weird to try). You can, however, if you need more control make your own join entity for many to many. In this case, defining your columns as fields and specifying those in the join should also work. Perhaps that's worth trying?

**Comment by cpaulit** [comment]
So, I fixed the mapping according to the tutorial documentation:

        mapping.forProperty('family').manyToOne({targetEntity: 'Family',
inversedBy: 'members'}).joinColumn({name: 'family_id'});

By the way, this also generates the same column mapping entry (which is
fine):

        mapping.forProperty('family').manyToOne({targetEntity: 'Family',
inversedBy: 'members'});

Both of those mapping definitions generate the following column definition:

        `family_id` int unsigned null

As you can see in both cases, the column name generated by the generator is
'family_id'.  No problem there.

My use case for the unique constraint is that in a database that allows
multiple families and one or more family members per family, I need a way
to make sure the name of each family member is unique per family.   Yes, a
join table could be implemented, but that's over-complicating a simple
need, which is a unique constraint on the family_id and name columns.  I
don't believe that is a weird database design; I've seen it used quite
frequently and is allowed in Java's default ORM (JPA).

However, independent of the database design question or preference, is the
problem (as I see it) of what the generator produces when you include the
following mapping definition:

        mapping.uniqueConstraint(['family', 'name']);

The generator has already determined (as in the second case from the top),
that the column name for the 'family' property is 'family_id'.  Again, no
problem there.  However, the unique constraint mapping in the above
snippet, as I have understood it, requires the property name, or it will
throw an exception--as you stated.  What the above code generates in the
DDL is the following:

        alter table `family_member` add unique
`family_member_family_name_unique`(`family`, `name`);

If the generator is going to map the 'family' property's column name to
'family_id' (whether explicitly told to or auto-determined), then I believe
the generator, which requires the property name in the array argument of
the .uniqueConstraint function, then the generator should produce the
'alter table' statement with the name of the column the generator already
produced in the 'create table' statement rather than producing the property
name as the name of the column.

**Comment by RWOverdijk** [comment]
I understand what you're saying, but it's not possible to set a unique constraint on a relation unless that column is one you design. I agree that it's probably best to figure out that the property is part of a relation, and map that column accordingly (so, family_id). This is something that needs to be added, but shouldn't be too difficult.

**Comment by RWOverdijk** [comment]
What you can do, is generate a unique index with a custom name and use family_id here specifically for now. It uses the literal value if it doesn't understand what it was given.

The solution here is to add a check in Mapper. If it's a relation, we have to return _all_ join columns (because it can be an array). If nothing was found, nothing should be returned.

* The call is being done here: https://github.com/SpoonX/wetland/blob/master/src/Mapping.ts#L479
* We need to add the check here: https://github.com/SpoonX/wetland/blob/master/src/Mapping.ts#L239 and return an array if needed
* We need to check the return value and merge, or skip, in case of array or null.

**Comment by RWOverdijk** [comment]
@cpaulit Is this relevant to you still? If so I can reopen. I know it'd be nice to support, eventually. It's just not a priority to me right now.
