### ISSUE TITLE
Safe seeding with custom check pattern

### ISSUE THREAD

**Issue by edouardmenayde** [SpoonX/wetland#210]
For the moment safe seeding check for all fields of the entity to avoid duplicate but it can be the source of problems in situation where a lifecylehooks changes some fields data. The solution is to let user specify the fields it wants the seeder to check.

@RWOverdijk Please just assign me, I created this not to forget it :)

**Comment by RWOverdijk** [comment]
@edouardmenayde You've been assigned 🗡
