### ISSUE TITLE
Dates always marked dirty

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/wetland#212]
It looks like when assigning a date, the compare goes wrong. We should probably add a conditional specifically to support this case. Something as simple as a time check, perhaps, to see if the date is different.

It's a small fix. Maybe fun for a new contributor.

**Update:**

This means that the unit of work basically _always_ marks dates as dirty.

**Comment by RWOverdijk** [comment]
@brniamut

**Comment by brniamut** [comment]
Yes, I'll be on it

**Comment by RWOverdijk** [comment]
@brniamut bump :)

**Comment by RWOverdijk** [comment]
@brniamut ... bump?
