### ISSUE TITLE
[Bug] mapping.joinColumn options

### ISSUE THREAD

**Issue by elxris** [SpoonX/wetland#215]
So, I've been tracking down a bug/problem I'm having with the migrator.

I'm trying something like this:
```js
mapping.forProperty('id').increments().primary()
mapping.forProperty('category').manyToOne({ targetEntity: 'Category', inversedBy: 'products' }).joinColumn({ nullable: false })
```
To get something like:
```sql
...
create table "products" ("id" serial primary key, "category" integer not null);
...
```
But, no matter how I try, I will always get a:
```sql
...
create table "products" ("id" serial primary key, "category" integer null);
...
```

I've been using de Nod.js Debugger, and I found that is the `snapshot.diff()` call that makes all wrong (called in [this](https://github.com/SpoonX/wetland/blob/d938f81a928fe5770c73c14d62dbcf6212ddb9c1/src/SchemaManager.ts#L84) line) because of this serializable
```json
"category": {
    "name": "category"
    "relationship": {
        ...
    },
    "joinColumn": {
        ...
        "nullable": false
    }
}
```

I always get: 
```
Object {name: "category", type: "integer", unsigned: true, nullable: true}
```

And I found in the source code [a line to blame](https://github.com/SpoonX/wetland/blob/d938f81a928fe5770c73c14d62dbcf6212ddb9c1/src/SnapshotManager.ts#L519)
Because it hardcodes the nullable, and actually in the docs it says is a parameter to `mapping#joinColumn`

I'm glad if this helps to track the problem, and I will found this very useful if it gets fixed soon, this will help to make my Identifying Relationships with a Surrogate ID Key like it says [this Stackoverflow](https://stackoverflow.com/questions/2814469/still-confused-about-identifying-vs-non-identifying-relationships) answer.

**Comment by RWOverdijk** [comment]
Thank you for the detailed report. I'll look into this as soon as possible. It should definitely be overridable, so I think this specific case doesn't merge mapping parameters yet. It should be fixed by changing it to:

`nullable: (typeof joinTable.nullable === 'boolean' ? joinTable.nullable : true)`

If you could test that, it would help a lot. Maybe even PR it, if you'd like to be marked as a contributor. You found the source of the problem after all, it's your credit.

**Comment by elxris** [comment]
I would love to make the PR.
A question, is not `joinColumn` instead of `joinTable` in the line of code you suggested?

**Comment by RWOverdijk** [comment]
@elxris Yes, sorry. It was around 2am when I wrote that :)
