### ISSUE TITLE
Duplicate primary key

### ISSUE THREAD

**Issue by jstans** [SpoonX/wetland#218]
Hi,

It seems I am having a recurring issue with duplicate primary key errors using a postgres database that is starting to cause some serious ramifications.

It is seemingly happening when two promises are resolving a .persist() at the same time. Waiting until all .persists() are resolved before flushing does not seem to be resolving the problem.

Out of interest why would wetland be trying to insert with a primary key value in the first place when the serial type is set to auto increment (serial)? Surely this opens the window for these issues if it is checking for a primary key to use prior to inserting a record rather than afterwards?

**Comment by RWOverdijk** [comment]
@jstans There are a couple of things in this issue that make no sense to me.

1. `.persist()` is sync. It doesn't return a promise
2. Wetland doesn't create PK values itself, it just sends in `null`

I think, once you answer those with more info, you'll find the problem somewhere in your own code. Maybe you're accidentally sending in IDs yourself? If so, please report back so I can close this issue. If not, do the same so I can assist you in finding the problem.

One thing to check, is the auto increment value of your schema. Perhaps you manually set it back to a value lower than the latest in your table.

**Comment by jstans** [comment]
@RWOverdijk Apologies for late response.

1. Whoops. Didn't even notice this (which is a little concerning) since the way I wrote the code it would have worked whether a value or a promise.
2. Good to know.

Unfortunately that's just made me more confused now! I'm definitely not supplying Ids in the code and it only happens occasionally. Could it be the way Knex is working for the PG driver I wonder? It's certainly acting like it's sending an ID on the INSERT; at least that is what the error message would suggest. I've refactored the code to call .flush less for now and am not currently seeing the problem but will definitely be doing some more testing on this once I've got a little more time (with knex debugging on) to work out where it's occurring. I was seeing a couple of other strange PG errors happening that seem to have stopped for now too.

Thanks

**Comment by RWOverdijk** [comment]
@jstans Try using `LOG_QUERIES=true` in front of whatever server you use. Example: 

`LOG_QUERIES=true node app.js`

**Comment by RWOverdijk** [comment]
Any update?

**Comment by jstans** [comment]
Since refactoring the code I haven't seen this happen at all yet. I can only imagine the issue was likely related to me potentially (and stupidly) using the same manager again in different contexts running at the same time. I think it makes more sense to close this issue unless I see it happen again. Sorry for the trouble!

**Comment by RWOverdijk** [comment]
No problem, glad you found our lord and savior Scope :)
