### ISSUE TITLE
Koa port pls

### ISSUE THREAD

**Issue by corysimmons** [SpoonX/wetland#219]
🙇

**Comment by RWOverdijk** [comment]
What do you mean "port"? It's easy enough to set it up yourself, isn't it? It's just the way you use this. I use wetland with async await, too. Not sure what you're asking :p

**Comment by corysimmons** [comment]
https://github.com/SpoonX/express-wetland but Koa. tbh, it's probably easy and I should do it. Just being lazy looking for handouts. :)

**Comment by RWOverdijk** [comment]
Ah! If you make such a thing let me know :)
