### ISSUE TITLE
Calculated Properties

### ISSUE THREAD

**Issue by captainjapeng** [SpoonX/wetland#224]
Hi, I'm new to Wetland, is it possible implement these features?

1. A Property/Field that's not persisted but the value is computed from other fields
2. Same with 1 but the value is persisted and in any way specify dependencies so when other values changed, the field/property will also be updated.

This feature is similar to Sequelize's Virtual Field with added feature of 2

**Comment by RWOverdijk** [comment]
Hello.

1. Yes. Entities are just regular classes. Feel free to create getters and even setters.
2. Also yes. It's a normal class. Create a setter that updates other values.
