### ISSUE TITLE
Documentation for decorators missing

### ISSUE THREAD

**Issue by s-hoff** [SpoonX/wetland#228]
The docs for decorators are not visible at https://wetland.spoonx.org. They already exists at https://github.com/SpoonX/wetland/blob/master/doc/decorators.md, so I suppose that the file only needs to be made visible in the gitbook.

**Comment by RWOverdijk** [comment]
@s-hoff Yes! The problem is that I haven't used them yet, and I don't know if they actually still work.

I'll be creating a new example app soon, using typescript. I'll test decorators then. I was hoping they'd come out of the draft stage soon, but no dice :(

**Comment by RWOverdijk** [comment]
I have published the docs with the last release. This issue can be closed.
