### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by SiddiquiImran** [SpoonX/wetland#231]
Hi,
I am following along with this tutorial:
https://wetland.spoonx.org/Tutorial/setting-up.html

but i got stuck with the Test the schema step as i am getting error if i try to run command 
wetland migrator schema -d

![image](https://user-images.githubusercontent.com/20870175/33267124-5305caa4-d39e-11e7-96d8-bb2e58c1104e.png)

even i have followed same steps as described.

I am using windows 10 system with node version 9.2.0 and npm version 5.5.1, Have also checked for CLI and CLI is already installed .

![image](https://user-images.githubusercontent.com/20870175/33267220-abc1413c-d39e-11e7-8a26-b327a8c2042d.png)

my repository url:
https://github.com/SiddiquiImran/wetland-test-demo

**Comment by RWOverdijk** [comment]
I've never tested this on windows. I wouldn't know why you get the error described. Could get some more info? The error isn't very descriptive.

**Comment by SiddiquiImran** [comment]
thanks @RWOverdijk ,

I will try in unix based machine and will let you know as i am getting this error only when I try to run that command

**Comment by RWOverdijk** [comment]
@SiddiquiImran Super! If you get further we can add windows support to the list, which would be amazing.

**Comment by RWOverdijk** [comment]
@SiddiquiImran Hey! Did you find anything new on this? I'm really curious.

**Comment by SiddiquiImran** [comment]
Hi @RWOverdijk ,

I just tested the flow in ubuntu and it's working fine.

for windows i tried for the error which is "microsoft jscript comiplation error", so  I followed various  solutions like one said install java and after taht it will work but the real link which worked is:

**Comment by RWOverdijk** [comment]
That's... New to me. Cool, glad you got it working!
