### ISSUE TITLE
[help]how can I update join field on ManyToOne relationship?

### ISSUE THREAD

**Issue by kyorry** [SpoonX/wetland#235]
I did not found the sample on docs on issue list.

I have 2 entities, product and category, category has many products.
eg. (product entity) 
`mapping.manyToOne('category', { targetEntity: 'Category', inversedBy: 'products' });`

how can I update product field category, the method did not work
`populator.assign(Product, req.body, data, true);`
before data is :
`{
  "id": 1,
  "category": { "id": 1, ... }
}`
I want to update the category to id 2, so I set the req.body is:
`{
  "id": 1,
  "category": { "id": 2, ... }
}`
I got the sql is:
`sql: 'update "product_category" set "id" = ? where "id" = ?' }`
The expected sql is :
`update "product" set "category_id" = 2`

how can i do it?

**Comment by RWOverdijk** [comment]
I'm having a difficult time understanding your question, so if I end up not answering it I do apologise.

First off, in your example you're updating all products to category 2. If that's your intention, you can simply do an update. The rest of my answer will assume you meant to update a specific entity.

If you wish to update a relationship, it's best to use wetland for that.  The populator, as cool as it is, is a tool that has some overhead, especially for this specific task. So if I understand correctly, you want to simply change the relation to whatever category has id 2 without first fetching the records from the database (sparing one or even two queries).

You could do this:

```js
const product  = manager.getReference('Product', 1);
const category = manager.getReference('Category', 2);

product.category = product;

manager.flush().then(/*...*/);
```

This will perform an update without fetching records first.

If you do wish to update _all_ records to product 2, you could use the querybuilder (you'd put this in a repository):

```js
const { EntityRepository } = require('wetland');

ProductRepository extends EntityRepository {
  updateProductsToCategory(categoryId) {
    return this.getQueryBuilder('p')
      .update({'category_id': categoryId})
      .getQuery()
      .execute();
  }
}
```

**Comment by kyorry** [comment]
Thank you so much for your prompt reply, this answer option 1 has solved my problem.

But I still have a question, why get the wrong sql result when using populator update?

**Comment by kyorry** [comment]
The update code:
`
populator.findDataForUpdate(id, Product, req.body)
    .then(data => {
      populator.assign(Product, req.body, data, true);
      return manager.flush().then(() => {
      });
    })
`
req.body data:
`
{
  "id": 1,
  "category": { "id": 2 }
}
`

**Comment by kyorry** [comment]
The update code:

```
populator.findDataForUpdate(id, Product, req.body)
    .then(data => {
      populator.assign(Product, req.body, data, true);
      return manager.flush().then(() => {
      });
    })
```
req.body data:
```
{
  "id": 1,
  "category": { "id": 2 }
}
```

**Comment by kyorry** [comment]
The update code:

```js
populator.findDataForUpdate(id, Product, req.body)
    .then(data => {
      populator.assign(Product, req.body, data, true);
      return manager.flush().then(() => {
      });
    })
```
req.body data:
```json
{
  "id": 1,
  "category": { "id": 2 }
}
```

got this sql:
```sql
'update "product_category" set "id" = ? where "id" = ?' }
```

**Comment by RWOverdijk** [comment]
It might be a bug. Could you post your code on gist or on a repository? Then I can reproduce it and see if it is in fact a bug.

**Comment by kyorry** [comment]
ok, i create a repository at:
https://github.com/kyorry/wetland-update

**Comment by RWOverdijk** [comment]
@kyorry Do you have any instructions on how to reproduce?

**Comment by kyorry** [comment]
1, create product and category, like this
```json
// categories
[{"name":"Apple"},{"name":"Microsoft"}]
// product
{
  "name": "ipad 11",
  "category": {
    "id": 1
  }
}
```
2, patch product:
```json
{
  "category": { "id": 2 }
}
```

**Comment by RWOverdijk** [comment]
So:

```sh
curl -XPOST -H 'Content-Type: application/json' -d '
  [{"name":"Apple"},{"name":"Microsoft"}]
' http://locahost:1337/category
```

then:

```sh
curl -XPOST -H 'Content-Type: application/json' -d '
{
  "name": "ipad 11",
  "category": {
    "id": 1
  }
}
' http://locahost:1337/product
```

And to break it: 

```sh
curl -XPOST -H 'Content-Type: application/json' -d '
{
  "category": { "id": 2 }
}' http://locahost:1337/product
```

Correct?

**Comment by kyorry** [comment]
```
patch, http://locahost:1337/product/1
```
Have you got the correct result?

**Comment by RWOverdijk** [comment]
@kyorry I'm sorry, I've been very busy. I haven't forgotten about this issue and I'll take a look at it asap.

**Comment by RWOverdijk** [comment]
Right off the bat I'm getting an error.

```
{
  "error": {
    "errno": 19,
    "code": "SQLITE_CONSTRAINT"
  }
}
```

**Comment by RWOverdijk** [comment]
It took me a while to figure this out, but this behaviour is correct.

You're passing in an object. So, it will try to update the id of an entity. This allows you to perform **nested updates**.

You want to do this:

```
curl -XPATCH -H 'Content-Type: application/json' -d '
{
  "category": 2
}' http://localhost:3000/product/1
```

I have verified that this yields the behaviour as described as expected by you.
