### ISSUE TITLE
How to do 3-level populator query?

### ISSUE THREAD

**Issue by kyorry** [SpoonX/wetland#236]
it does't support the populator:
```js
repository.find({name: 'Wesley'} , {populate: ['project', 'project.task', 'project.task.owner']});
```
The populator only support ['project', 'project.task'] now.

**Comment by RWOverdijk** [comment]
It does, but you have to define aliases or use the table name. So, it's this:

```js
repository.find({name: 'Wesley'} , {populate: ['project', 'project.task', 'task.owner']});
```

Join us on Gitter, github issues is not the place for questions like this.

https://gitter.im/SpoonX/Dev

**Comment by kyorry** [comment]
but, i got this error: Cannot find the reference mapping for 'task', are you sure you registered it first?

**Comment by kyorry** [comment]
I'm not sure is the issue on this code, QueryBuilder line 269:
```js
if (join.type !== Mapping_1.Mapping.RELATION_MANY_TO_MANY && join.type !== Mapping_1.Mapping.RELATION_ONE_TO_MANY) {
            return parentQueryBuilder.leftJoin(column, targetAlias);
        }
```
it did not set in queryBuilders, so getChild will return none.

**Comment by kyorry** [comment]
@RWOverdijk 
i create a repository to reproduce the problem, the link is: https://github.com/kyorry/wetland-query

Reproduce step:
1, node app
2, get http://localhost:3000/category


```
Error: Cannot find the reference mapping for 'owner', are you sure you registered it first?
```

**Comment by RWOverdijk** [comment]
Please read my replies.

*Join us on Gitter, Github issues is not the place for questions like this.*

https://gitter.im/SpoonX/Dev

**Comment by RWOverdijk** [comment]
@kyorry To answer your question (for future googlers) this doesn't work with many associations. Those are individual query builders and you'd have to register the joins on there. One option is to expand the repository by creating a map of querybuilders. I can walk you through the steps on gitter.

Basically you'd store the query builder here: https://github.com/SpoonX/wetland/blob/master/src/EntityRepository.ts#L151

And use it when available.
