### ISSUE TITLE
Postgres JSON query support

### ISSUE THREAD

**Issue by jstans** [SpoonX/wetland#242]
Can we use JSON query support at all? I can't find any reference to it anywhere.

I understand why it may not be supported since it's currently specific to a particular variant of SQL that some people may not be using, but could we possibly look at adding support for it if the correct driver is used? If not, could we expose the knex object in order to add a manual raw where condition for use cases where it is required?

**Comment by RWOverdijk** [comment]
Hey!

There's support for the json type (for schema). Just set the type and it'll use knex's `.json()`. As to querying, there isn't specifically, no. But you can already get the knex instance by using getStatement (the knex querybuilder).

```js
querybuilder.getStatement() // Probably in your repository
```

Some options can be passed in through select, what are you trying to do? Perhaps I can help.

**Comment by jstans** [comment]
Ah I didn't realise .GetStatement() was an exact instance of knex as the documentation only mentions query builder. I'll give that a try later.

Basically I am just trying to add where conditions based on values contained in json. So json_column->data->>value in postgres schema. To my knowledge there is no native support in knex even and you would need to use .whereRaw().

**Comment by jstans** [comment]
Using knex directly works, though obviously it's a shame to lose the functionality of the Entitity Repository etc.

```javascript
const data = await manager.getRepository('Table').getQueryBuilder('t').prepare().getStatement().whereRaw("column->>'key'=?",['value'])
```

A better description of the json operators etc can be found here https://www.postgresql.org/docs/9.5/static/functions-json.html

I'm guessing the reason knex itself doesn't have native functions is because it originally was postgres only, though I believe at least SQL Server (which knex has recently adopted) and MariaDB have both added functions for querying JSON (though not as native QL operators).

**Comment by RWOverdijk** [comment]
That syntax is quite interesting. We could add custom where clauses for this, which would be a nice feature. Defining your own types and clause builders. Are you interested in giving that a go? Making a custom method (patching wetland) and then we build the tools around it to make it easier.

https://github.com/SpoonX/wetland/blob/master/src/Criteria/Criteria.ts#L14 there are operators here, perhaps we can make a new operator?

Otherwise we can also create a way to provide a custom Where builder? https://github.com/SpoonX/wetland/blob/master/src/QueryBuilder.ts#L118

I think having plugins for this stuff would be nice.

**Comment by jstans** [comment]
So my first thought would have been to add extra operators e.g. jsonEquals, jsonContains and then supplying a json object. Replicating the postgres operators would be another possibility. You could then go a step further and utilise the functions provided in other dialects, though this would bump up the minimum version and potentially cause some confusion; perhaps a warning in the documentation at least.

Another idea I had before that, that would add flexibility and relevant errors in this case was essentially an analysis pass to detect support after connecting, but most ORMs don't seem to do this, probably for good reason. There's also potentially something to learn from other ORMs that seem to have come up with something already for this.

This is certainly something I would like to look at given a bit more time.

**Comment by RWOverdijk** [comment]
Yes, that's because it's impossible given the multi-adapter nature of wetland. You can have data in databases from different vendors and it'll still work.

I think this might be a case for knex plugins.

**Comment by RWOverdijk** [comment]
@jstans This issue will be marked as stale soon. I'll close this now. If you have more questions, let me know! :)
