### ISSUE TITLE
Error for oneToMany Relations: { Error: SQLITE_ERROR: near "(": syntax error errno: 1, code: 'SQLITE_ERROR' }

### ISSUE THREAD

**Issue by wsjwa** [SpoonX/wetland#247]
Tested on a sqlite Database.

Configuration:
oneToMany Relation with joinColumn: Category
manyToOne Relation with joinColumn: Products

If you query the Category and populate the Products you will get this error:
{ Error: SQLITE_ERROR: near "(": syntax error errno: 1, code: 'SQLITE_ERROR' }

There is no problem if you query Products and populate the Category.

Query Method: find()

**Comment by wsjwa** [comment]
I'll paste some code tomorrow. Gotta go

**Comment by wsjwa** [comment]
Example for category and products. Error occurs when you try to select categories and poulate products with product name field in the where condition.

`
static setMapping(mapping) {

		mapping.entity({store: 'defaultcon', repository: CategoryRepository, tableName: 'category'});

		mapping.forProperty('id').primary();

		mapping.field('name', {
			type: 'string',
			name: 'name',
			size: 255
		});

		mapping.oneToMany('category_produkt', {targetEntity: 'Product', mappedBy: 'produkt_category'});
		mapping.joinColumn('category_produkt', {name: 'id', referencedColumnName: 'category_id', type: 'integer'});
	}
	
	
	static setMapping(mapping) {

		mapping.entity({store: 'defaultcon', repository: ProductRepository, tableName: 'product'});

		mapping.forProperty('id').primary();

		mapping.field('name', {
			type: 'string',
			name: 'name',
			size: 255
		});

		mapping.manyToOne('produkt_category', {targetEntity: 'Category', inversedBy: 'category_produkt'});
		mapping.joinColumn('produkt_category', {name: 'category_id', referencedColumnName: 'id', type: 'integer'});
	}`

**Comment by RWOverdijk** [comment]
@wsjwa Thanks.

you might be interested in joining our slack, where I generally answer a bit faster. Also it makes talking about this easier. :) 


[Sign up here](https://spoonx-slack.herokuapp.com)
