### ISSUE TITLE
Errors when using a primary key that is not an integer

### ISSUE THREAD

**Issue by bluemaex** [SpoonX/wetland#260]
Hi,

**Describe the bug**
If I am using entities with a primary key that is not an integer (for example a UUID) persisting data does not work as expected :/
 Inserting Data (aka the SQL Query) in the database works perfectly, but after persisting and refreshing the Entity-Instance from the database result the primary key is always set to zero, instead of the value that we set manually before persisting.

**To Reproduce**

I am using this Entity (shortened to necessary code)
```js
class User extends Entity {
  static setMapping(mapping) {
    mapping
      .forProperty('id')
      .primary()
      .field({ type: 'uuid', nullable: false })

    mapping.field('username', { type: 'string', size: 100, nullable: false })
  }
```

and using it in the application as following to insert data:

```js
    const manager = wetland.getManager()

    const newUser = new User()
    newUser.id = '<own-generated-uuid-value>'
    newUser.username = 'Wesley'

    await manager.persist(newUser).flush()
```

The app crashes with the following exception:

```
Error: Cannot refresh entity without a PK value.
        at entity.forEach.toRefresh (~/api/node_modules/wetland/dist/src/Scope.js:106:54)
        at Array.forEach (<anonymous>)
        at Scope.refresh (~/api/node_modules/wetland/dist/src/Scope.js:101:16)
        at UnitOfWork.refreshNew (~/node_modules/wetland/dist/src/UnitOfWork.js:582:35)
```

**Expected behavior**

No exception, expected that the call returns success and that the entity is refreshed after creation.

**Environment (please complete the following information):**
 - Node.js version: 10.10
 - Adapter: mysql2
 - Version: 4.1.2

**Additional context**

I tried to find the culprit in the source code and found a way how this error can be avoided. As I understood the code it currently always set the primary key after a successful database insert. 
I added a check to the ``refreshNew`` function, to check if the field is an autogenerated value and only then set the value to the return of the database call: https://github.com/bluemaex/wetland/commit/9af791706c745860ebf48cb33bf99133d7474d34

I am not sure if I missed another place, if yes I happily will add that and do a Pull Request 👍

**Comment by RWOverdijk** [comment]
Hey @bluemaex! Nice job on finding the one thing I'm not happy about in Wetland haha.

Primary keys are too focused on being named `id` and having an integer value. I personally haven't used uuids in wetland as PK value yet so I've never encountered this before. But I knew it was an issue.

I'd like to have this fixed, but I'm currently knees deep in stix framework. If you're up for helping out, that would be amazing. Maybe join us on slack so we can talk about the steps to take? 


[![Slack Status](https://spoonx-slack.herokuapp.com/badge.svg)](https://spoonx-slack.herokuapp.com)

**Comment by bluemaex** [comment]
I guess I hit the jackpot in this case 😀 

I'll join the slack, happy to help!
