### ISSUE TITLE
Wrong database field type on relation when primary key is not an integer

### ISSUE THREAD

**Issue by bluemaex** [SpoonX/wetland#261]
**Describe the bug**
If you create two entities and their primary key is not an integer, the schemabuilder generates always an joinColumn with the type 'integer' and 'unsigned' instead of using the field type of the foreign key column.

Due to the wrong field type mysql emmits an cryptic error during creation of the foreign key that the database column does not exists.

**To Reproduce**

```js
class Customer extends Entity {
  static setMapping(mapping) {
    mapping
      .forProperty('id')
      .field({ type: 'uuid', nullable: false })
      .primary()

    mapping.field('name', { type: 'string', size: 100, nullable: false })
    mapping.oneToMany('segments', { targetEntity: CustomerSegment, mappedBy: 'customer' })
  }
}
```
```js
class CustomerSegment extends Entity {
  static setMapping(mapping) {
    mapping
      .forProperty('id')
      .field({ type: 'uuid', nullable: false })
      .primary()

    mapping.field('name', { type: 'string', size: 100, nullable: false })
    mapping.manyToOne('customer', { targetEntity: Customer, inversedBy: 'segments' })
  }
}
```

it generates the following sql when used via the wetland-cli tool ``wetland migrator schema -d``:
```sql
create table `customersegment` (`id` char(36) not null, `name` varchar(100) not null, `customer_id` int unsigned null);
alter table `customersegment` add primary key `customersegment_pkey`(`id`);
```

**Expected behavior**

That the generated Shapshot SQL is using the same field type for the join column as the foreign key column itself also has.

```sql
create table `customersegment` (`id` char(36) not null, `name` varchar(100) not null, `customer_id` char(36) null);
alter table `customersegment` add primary key `customersegment_pkey`(`id`);
```

**Environment (please complete the following information):**
 - Node.js version: 10.10
 - Adapter: mysql2
 - Version: 4.1.2

**Additional context**

I found the culprit in the code that the unsigned integer code was hardcoded. After changing the particular code to get the field type definition from the joinColumn it generated correct the SQL - 
https://github.com/bluemaex/wetland/commit/553ce79824ea6e3b93ef019afc4dfca60780e9ea

However I am not sure if that is the right approach or the only place where to change this? I'll happy do a pull request if :)

**Comment by RWOverdijk** [comment]
My reply to this issue would be the same as my reply on the other issue. I'd like to talk about this and find a solution. I'll re-paste the slack link 😄 

[![Slack Status](https://spoonx-slack.herokuapp.com/badge.svg)](https://spoonx-slack.herokuapp.com)

**Comment by bluemaex** [comment]
thanks for the reminder stale-bot 👍

**Comment by RWOverdijk** [comment]
Good boy bot! *pat pat*
