### ISSUE TITLE
Documment is not enough.

### ISSUE THREAD

**Issue by jnst** [SpoonX/wetland#263]
I think Wetland seems to be a good design than `TypeORM` and I think Wetland has lots of excellent features like `Unit of Work`.
However, there seems to be a shortage of documents for actually runnning, and especially since TypeScript code samples are few, I gave up before running the sample code.

In addition, the code before substitution is displayed in the document. `{% endmethod %}`
https://github.com/SpoonX/wetland/blob/master/doc/API/unit-of-work.md

**Comment by RWOverdijk** [comment]
@jnst The docs are hosted on gitbook: https://wetland.spoonx.org it's much more readable there.
