### ISSUE TITLE
elastic

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/wetland#4]
https://github.com/doctrine/search

**Comment by Shakyamuni177te** [comment]
Does this library currently need implementing into wetland?

**Comment by RWOverdijk** [comment]
That specific library doesn't, because it's for php. The map towards this specific issue is:

- Implement cascade remove (#75)
- Implement eventmanager (#18)
- Implement elasticsearch plugin (#4)

The elasticsearch plugin will then allow you to set up auto-synced mappings.

**Comment by RWOverdijk** [comment]
I've experimented with this for a while now, and the number of edge cases make this plugin not worth the time. It's best to set it up yourself.
